// types.ts

export interface BaseEntity {
    id: number | string; // bigint in PostgreSQL
    created_at: string;  // timestamptz ISO string
    updated_at: string;  // timestamptz ISO string
  }
  
  // ==========================================
  // 1. USERS
  // ==========================================
  export interface User extends BaseEntity {
    first_name: string;
    last_name: string;
    username: string;
    email: string;
    phone: string | null;
    status: boolean;
  }
  
  export interface CreateUserInput {
    first_name: string;
    last_name: string;
    username: string;
    email: string;
    phone?: string | null;
    status?: boolean;
  }
  
  export type UpdateUserInput = Partial<CreateUserInput>;
  
  // ==========================================
  // 2. CUSTOMERS
  // ==========================================
  export interface Customer extends BaseEntity {
    code: number;
    name: string;
    phone: string | null;
    email: string | null;
    country: string | null;
    city: string | null;
    address: string | null;
    tax_number: string | null;
    total_sale_due: number | string;        // numeric(14,2)
    total_sell_return_due: number | string; // numeric(14,2)
  }
  
  export interface CreateCustomerInput {
    code?: number; // Optional if auto-generated by your backend
    name: string;
    phone?: string | null;
    email?: string | null;
    country?: string | null;
    city?: string | null;
    address?: string | null;
    tax_number?: string | null;
    total_sale_due?: number;
    total_sell_return_due?: number;
  }
  
  export type UpdateCustomerInput = Partial<CreateCustomerInput>;
  
  // ==========================================
  // 3. SUPPLIERS
  // ==========================================
  export interface Supplier extends BaseEntity {
    code: number;
    name: string;
    phone: string | null;
    email: string | null;
    country: string | null;
    city: string | null;
    address: string | null;
    tax_number: string | null;
    total_purchase_due: number | string;        // numeric(14,2)
    total_purchase_return_due: number | string; // numeric(14,2)
  }
  
  export interface CreateSupplierInput {
    code?: number; // Optional if auto-generated by your backend
    name: string;
    phone?: string | null;
    email?: string | null;
    country?: string | null;
    city?: string | null;
    address?: string | null;
    tax_number?: string | null;
    total_purchase_due?: number;
    total_purchase_return_due?: number;
  }
  
  export type UpdateSupplierInput = Partial<CreateSupplierInput>;
  
  // ==========================================
  // 4. API & SERVER ACTION RESPONSES
  // ==========================================
  export interface ActionResponse<T = unknown> {
    success: boolean;
    data?: T;
    error?: string;
  }